### ISSUE TITLE
keys.plist

### ISSUE THREAD

**Issue by moh1122** [mog96/the-delt-ios#1]
Hello
I like your project but when im building it the file keys.plist is missing any clue ?

**Comment by mog96** [comment]
Appreciate your interest!! I currently have the app in TestFlight for use
in my fraternity, and the Keys.plist file has some private keys I use for
the app. Sorry about that! Not sure what a good workaround would be...

**Comment by caijim** [comment]
Just make your own keys.plist file and connect it to parse

**Comment by moh1122** [comment]
ok and what will tht include
Client ID and APP ID only or any other ?

**Comment by caijim** [comment]
just run the code and see what it extracts from it
